modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/Crimix/TabStats/issues"
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

[[mods]] #mandatory
modId="tabstats"
authors="black_dog20"
displayURL="https://minecraft.curseforge.com/projects/tab-stats"
version="${version}"
displayName="Tab Stats"
updateJSONURL="${update_url}"
logoFile="tabstats-logo.png"
credits="To all my friends for putting up with me breaking the server multiple times during testing"
description='''

'''

[[dependencies.tabstats]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tabstats]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
